zuul:
  ignoredServices: '*'
  prefix: /api/v1
  routes:
    none-user:
      path: /nuser/**
      serviceId: nu-service
      strip-prefix: false
    user:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
    mod:
      path: /mod/**
      serviceId: mod-service
      strip-prefix: false
    admin:
      path: /admin/**
      serviceId: admin-service
      strip-prefix: false

eureka :
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost